name: Build

on:
  push:
    branches: [main]
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build frontend
        uses: ./.github/actions/build-frontend

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.4"
          python-version: "3.9"

      - name: Build Python package
        run: uv build --no-sources

      - uses: actions/upload-artifact@v4
        with:
          name: package-dist
          path: dist/

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.4"
          python-version: "3.9"

      - name: Build Sphinx docs
        run: |
          uv run --group docs --frozen \
            sphinx-build docs/ docs/_build/ \
              --builder html \
              --fail-on-warning \
              --color \
              --verbose

      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/_build/html

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    environment:
      name: pypi
      url: https://pypi.org/p/streamlit-arborist
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Download package distributions
        uses: actions/download-artifact@v4
        with:
          name: package-dist
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
