name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.4"
          python-version: "3.9"

      - name: Run pre-commit hooks
        run: uvx pre-commit@4.2.0 run --show-diff-on-failure --color=always --all-files

  pytest:
    runs-on: ubuntu-latest
    needs: [pre-commit]
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Build frontend
        uses: ./.github/actions/build-frontend

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.4"
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: uv run --group tests --frozen playwright install firefox chromium

      - name: Run tests
        run: uv run --group tests --frozen pytest --browser firefox --browser chromium
